### ISSUE TITLE
Suggestion to simplify the Tasmota IR command script

### ISSUE THREAD

**Issue by bwarden** [digiblurDIY/Website#27]
I followed your guide with great success, using the uniplay IR blaster, after I finally got my makeshift pogo pins (just a strip of 7 header pins) pressed just right on the test points to flash the firmware with `esptool`.

Regarding the sample script you provided for your TV:
https://github.com/digiblurDIY/Website/blob/dc25b0d7ad8468dbefa8bcca85eaf49c47dfc913/docs/devices/other/Tasmota-Infrared-Remote.md?plain=1#L160-L582

It can be simplified a great deal by setting the individual IR command payloads in a single dictionary, indexed by command, then using a single templated service call like this:

```yaml
jvc_tv:
  alias: Remote - JVC TV
  icon: mdi:remote
  mode: single
  fields:
    command:
      description: IR Command Alias
      example: power_on
    mqtttopic:
      description: MQTT Topic for Tasmota IR blaster
      example: cmnd/irblaster/IRSend
  sequence:
  - variables:
      commands:
        power: '{"Protocol":"JVC","Bits":16,"Data":0xC0E8,"Repeat":10}'
        hdmi: '{"Protocol":"JVC","Bits":16,"Data":0xC0A8}'
        input: '{"Protocol":"JVC","Bits":16,"Data":0xC0C8}'
        mute: '{"Protocol":"JVC","Bits":16,"Data":0xC038}'
        volume_down: '{"Protocol":"JVC","Bits":16,"Data":0xC0F8}'
        volume_up: '{"Protocol":"JVC","Bits":16,"Data":0xC078}'
        enter: '{"Protocol":"JVC","Bits":16,"Data":0xC050}'
  - service: mqtt.publish
    data:
      topic: '{{ mqtttopic }}'
      payload: '{%if command in commands %}{{ commands[command] }}{% endif %}'
```
If the command isn't in the dictionary, Tasmota will harmlessly warn about an empty payload to `IRSend`. Obviously, you could still use your preferred raw payloads.
